### ISSUE TITLE
if a error occurs while create a endpoint, no http response is send

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#120]
If you create a endpoint, and for example the schema validation faid, no http response is send to the client.

```
[2022.04.23 - 18:56.16.012][verbose][endpoints] add(); Pre hooks aborted
Error: Command validation failed: ValidationError: "interface" is required
    at /home/marc/projects/OpenHaus/backend/components/endpoints/index.js:81:31
    at Array.forEach (<anonymous>)
    at Middleware.<anonymous> (/home/marc/projects/OpenHaus/backend/components/endpoints/index.js:72:31)
    at Middleware.<anonymous> (/home/marc/projects/OpenHaus/backend/system/middleware.js:149:24)
    at value (/home/marc/projects/OpenHaus/backend/system/middleware.js:78:20)
    at Middleware.<anonymous> (/home/marc/projects/OpenHaus/backend/system/middleware.js:116:17)
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:64:35
    at new Promise (<anonymous>)
    at preHooks (/home/marc/projects/OpenHaus/backend/system/component/class.common.js:51:28)
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:130:32
[2022.04.23 - 18:56.16.012][debug][endpoints] add(); Function stack catched/rejected
```

**Comment by mStirner** [comment]
Could not reproduce. Keep this open & add dateset when error occurs again.
(Perhaps im not drunk enough :wink:)

**Comment by mStirner** [comment]
```
TypeError: Cannot read properties of undefined (reading 'map')
    at new Endpoint (/home/marc/projects/OpenHaus/backend/components/endpoints/class.endpoint.js:35:38)
    at Middleware.<anonymous> (/home/marc/projects/OpenHaus/backend/components/endpoints/index.js:63:24)
    at Middleware.<anonymous> (/home/marc/projects/OpenHaus/backend/system/middleware.js:149:24)
    at value (/home/marc/projects/OpenHaus/backend/system/middleware.js:78:20)
    at Middleware.<anonymous> (/home/marc/projects/OpenHaus/backend/system/middleware.js:116:17)
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:98:36
    at new Promise (<anonymous>)
    at postHooks (/home/marc/projects/OpenHaus/backend/system/component/class.common.js:85:28)
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:162:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Input:
```js
{
    "name":"HDMI Switcher",
    "device":"626711a0f2829820701c6ea8",
    "commands":[
        {
            "name":"HDMI 01",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i01\r\n",
            "alias":"HDMI_01"
        },
        {
            "name":"HDMI 02",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i02\r\n",
            "alias":"HDMI_02"
        },
        {
            "name":"HDMI 03",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i03\r\n",
            "alias":"HDMI_03"
        },
        {
            "name":"HDMI 04",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i04\r\n",
            "alias":"HDMI_04"
        },
        {
            "name":"HDMI 05",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i05\r\n",
            "alias":"HDMI_05"
        },
        {
            "name":"HDMI 06",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i06\r\n",
            "alias":"HDMI_06"
        },
        {
            "name":"HDMI 07",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i07\r\n",
            "alias":"HDMI_07"
        },
        {
            "name":"HDMI 08",
            "interface":"626711a0f2829820701c6ea9",
            "payload":"sw i08\r\n",
            "alias":"HDMI_08"
        }
    ]
}
```

No http response is send.
