### ISSUE TITLE
WebSocket tunneling over/through stream pipeline not possible

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#128]
Something like "RSV2 & RSV3" must be clear.

https://stackoverflow.com/a/45304511/5781499

```
Error message RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:171:14)
    at Receiver.startLoop (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Duplexify.socketOnData (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/websocket.js:1141:35)
    at Duplexify.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'WS_ERR_UNEXPECTED_RSV_2_3',
  [Symbol(status-code)]: 1002
}
```

**Comment by mStirner** [comment]
When adapter are involved, it seems the error occurs:

```js
    attach(upstream) {

        let stack = this.adapter.map((name) => {
            try {

                return require(path.resolve(process.cwd(), "adapter", `${name}.js`))();

            } catch (err) {

                console.error(`Error in adapter "${name}" `, err);

            }
        });

        let stream = new Adapter(stack, upstream, {
            // duplex stream options
            emitClose: false,
            end: false
        });

        this.event.emit("timestamp", Date.now());

        console.log(`${this._id}: attached`);
        //this.stream = upstream;
        this.stream = stream;

        nextTick(() => {
            //this.event.emit("attached", upstream);
            this.event.emit("attached", stream);
        });

    }
```

This works:
```js
    attach(upstream) {

        let stack = this.adapter.map((name) => {
            try {

                return require(path.resolve(process.cwd(), "adapter", `${name}.js`))();

            } catch (err) {

                console.error(`Error in adapter "${name}" `, err);

            }
        });

        /*
        let stream = new Adapter(stack, upstream, {
            // duplex stream options
            emitClose: false,
            end: false
        });*/
        let stream = upstream;

        this.event.emit("timestamp", Date.now());

        console.log(`${this._id}: attached`);
        //this.stream = upstream;
        this.stream = stream;

        nextTick(() => {
            //this.event.emit("attached", upstream);
            this.event.emit("attached", stream);
        });

    }
```

**Comment by mStirner** [comment]
In a minimal reproducible example no error occur....
https://gist.github.com/mStirner/223bf0902aafde2da16fac6f9757975f

**Comment by mStirner** [comment]
Seems like has something to do with the stream options that are set.
```js

....

    let upstream = WebSocket.createWebSocketStream(ws, {
        // duplex stream options
        //emitClose: false,
        //objectMode: true,
        //decodeStrings: false
        //allowHalfOpen: true
    });

    let options = {
        //emitClose: false,       // false
        //decodeStrings: false,    // false
        encoding: "utf8",
        //objectMode: false    // true
    }

    let readable = new PassThrough(options);
    let writable = new PassThrough(options);

    let duplex = Duplex.from({
        readable,
        writable
    });

    let { encode, decode } = require("./adapter.js")(options);

    //upstream.pipe(decode).pipe(readable);
    //duplex.pipe(encode).pipe(upstream);

    upstream.pipe(decode).pipe(readable);
    writable.pipe(encode).pipe(upstream);


    require("./client")(duplex);

....

```

With encoding = "utf8" this happens.

**Comment by mStirner** [comment]
If its commented out/not set, pioneer/eiscp commands are not working any more. When its set WebSocket connections are broken... :cursing_face:

![fdd](https://user-images.githubusercontent.com/5003424/165384776-0bd54925-02e1-4078-bbf0-b19b0c0d4ea9.gif)

**Comment by mStirner** [comment]
Removed options from https://github.com/OpenHausIO/backend/blob/dev/adapter/eiscp.js
```
encoding: "utf8",
objectMode: true
```

Added string conversion in adapter & commented out https://github.com/OpenHausIO/backend/blob/dev/components/devices/class.adapter.js#L25

This is how both works, but not satisfying.
This needs to be refactored!
