### ISSUE TITLE
Pump & Dumb Error message

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#185]
```
Unknwon type
UNKNOWN SSDP MESSAGE
/home/marc/projects/OpenHaus/backend/routes/router.api.ssdp.js:48
        throw new Error(`unknown ssdp message type ${type}`);
              ^

Error: unknown ssdp message type location: http://192.168.2.4:80/description.xml
    at parseHeader (/home/marc/projects/OpenHaus/backend/routes/router.api.ssdp.js:48:15)
    at WebSocket.<anonymous> (/home/marc/projects/OpenHaus/backend/routes/router.api.ssdp.js:137:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mStirner** [comment]
```

**Comment by mStirner** [comment]
Happened since opening this issue not again.
