### ISSUE TITLE
Custom command handler does not work after `/endpoints` is fetched

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#196]
When a custom handler is set for a command, and the `<host>/api/endpoints` resources is fetched (`GET`), the custom command handler gets overriden.

```
socket.ref called
request response [ { success: { '/lights/1/state/on': false } } ]
socket.setKeepAlive called true 3000
socket.unref called
socket.setTimeout called 0






User request: null false false 127.0.0.1 GET /endpoints/
User request: null false false 127.0.0.1 POST /endpoints/633481e928a62d4bb14edf00/commands/633481e928a62d4bb14edf01
commnads hanlder size: Map(0) {}
EXECUTE COMMAND!!!!! 633481e928a62d4bb14edf01
Error: Command payload not defined
Add payload to command or write a plugin that implement the command handling
    at Commands.execute (/home/marc/projects/OpenHaus/backend/components/endpoints/class.commands.js:142:27)
    at /home/marc/projects/OpenHaus/backend/routes/router.api.endpoints.js:28:27
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:284:15
    at param (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:365:14)
    at param (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:376:14)
    at paramCallback (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:412:21)
```

**Comment by mStirner** [comment]
After calling /endpoints, *every* command handler is gone.

```
socket.ref called
request response [ { success: { '/lights/1/state/on': false } } ]
socket.setKeepAlive called true 3000
socket.unref called
socket.setTimeout called 0
User request: null false false 127.0.0.1 GET /endpoints
Endpoint commands [
  Map(2) {
    '633481e928a62d4bb14edf01' => [Function (anonymous)],
    '633481e928a62d4bb14edf02' => [Function (anonymous)]
  },
  Map(2) {
    '633481e928a62d4bb14edf04' => [Function (anonymous)],
    '633481e928a62d4bb14edf05' => [Function (anonymous)]
  },
  Map(2) {
    '633481e928a62d4bb14edf07' => [Function (anonymous)],
    '633481e928a62d4bb14edf08' => [Function (anonymous)]
  },
  Map(2) {
    '633481e928a62d4bb14edf0a' => [Function (anonymous)],
    '633481e928a62d4bb14edf0b' => [Function (anonymous)]
  },
  Map(2) {
    '633481e928a62d4bb14edf0d' => [Function (anonymous)],
    '633481e928a62d4bb14edf0e' => [Function (anonymous)]
  },
  Map(2) {
    '633481e928a62d4bb14edf10' => [Function (anonymous)],
    '633481e928a62d4bb14edf11' => [Function (anonymous)]
  },
  Map(0) {},
  Map(0) {},
  Map(2) {
    '633481e928a62d4bb14edf19' => [Function (anonymous)],
    '633481e928a62d4bb14edf1a' => [Function (anonymous)]
  },
  Map(0) {},
  Map(2) {
    '633481e928a62d4bb14edf1f' => [Function (anonymous)],
    '633481e928a62d4bb14edf20' => [Function (anonymous)]
  },
  Map(0) {},
  Map(2) {
    '633481e928a62d4bb14edf25' => [Function (anonymous)],
    '633481e928a62d4bb14edf26' => [Function (anonymous)]
  },
  Map(0) {}
]
User request: null false false 127.0.0.1 POST /endpoints/633481e928a62d4bb14edf00/commands/633481e928a62d4bb14edf01
commnads hanlder size: Map(0) {}
EXECUTE COMMAND!!!!! 633481e928a62d4bb14edf01
Error: Command payload not defined
Add payload to command or write a plugin that implement the command handling
    at Commands.execute (/home/marc/projects/OpenHaus/backend/components/endpoints/class.commands.js:142:27)
    at /home/marc/projects/OpenHaus/backend/routes/router.api.endpoints.js:28:27
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:284:15
    at param (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:365:14)
    at param (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:376:14)
    at paramCallback (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:412:21)
User request: null false false 127.0.0.1 GET /endpoints
Endpoint commands [
  Map(0) {}, Map(0) {},
  Map(0) {}, Map(0) {},
  Map(0) {}, Map(0) {},
  Map(0) {}, Map(0) {},
  Map(0) {}, Map(0) {},
  Map(0) {}, Map(0) {},
  Map(0) {}, Map(0) {}
]
```

Code for output, `rest-handler.js`, in route "/:_id?"
```js
            let cmds = C_COMPONENT.items.map((endpoint) => {
                return endpoint.commands?.handler;
            })

            console.log("Endpoint commands", cmds);
```

**Comment by mStirner** [comment]
Seems like the commands array is new created when route is called. But why?!

```
User request: null false false 127.0.0.1 GET /endpoints
Endpoint commands
Endpoint 633481e928a62d4bb14edf00
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf01' => [Function (anonymous)],
  '633481e928a62d4bb14edf02' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf03
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf04' => [Function (anonymous)],
  '633481e928a62d4bb14edf05' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf06
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf07' => [Function (anonymous)],
  '633481e928a62d4bb14edf08' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf09
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf0a' => [Function (anonymous)],
  '633481e928a62d4bb14edf0b' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf0c
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf0d' => [Function (anonymous)],
  '633481e928a62d4bb14edf0e' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf0f
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf10' => [Function (anonymous)],
  '633481e928a62d4bb14edf11' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf12
Item createion timesta 1664701641813
Map(0) {}
Endpoint 633481e928a62d4bb14edf15
Item createion timesta 1664701641813
Map(0) {}
Endpoint 633481e928a62d4bb14edf18
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf19' => [Function (anonymous)],
  '633481e928a62d4bb14edf1a' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf1b
Item createion timesta 1664701641813
Map(0) {}
Endpoint 633481e928a62d4bb14edf1e
Item createion timesta 1664701641813
Map(2) {
  '633481e928a62d4bb14edf1f' => [Function (anonymous)],
  '633481e928a62d4bb14edf20' => [Function (anonymous)]
}
Endpoint 633481e928a62d4bb14edf21
Item createion timesta 1664701641814
Map(0) {}
Endpoint 633481e928a62d4bb14edf24
Item createion timesta 1664701641814
Map(2) {
  '633481e928a62d4bb14edf25' => [Function (anonymous)],
  '633481e928a62d4bb14edf26' => [Function (anonymous)]
}
Endpoint 633889e10123935a23e98f79
Item createion timesta 1664701641814
Map(0) {}
User request: null false false 127.0.0.1 GET /endpoints
Endpoint commands
Endpoint 633481e928a62d4bb14edf00
Item createion timesta 1664701658372
Map(0) {}
Endpoint 633481e928a62d4bb14edf03
Item createion timesta 1664701658372
Map(0) {}
Endpoint 633481e928a62d4bb14edf06
Item createion timesta 1664701658372
Map(0) {}
Endpoint 633481e928a62d4bb14edf09
Item createion timesta 1664701658373
Map(0) {}
Endpoint 633481e928a62d4bb14edf0c
Item createion timesta 1664701658374
Map(0) {}
Endpoint 633481e928a62d4bb14edf0f
Item createion timesta 1664701658374
Map(0) {}
Endpoint 633481e928a62d4bb14edf12
Item createion timesta 1664701658374
Map(0) {}
Endpoint 633481e928a62d4bb14edf15
Item createion timesta 1664701658375
Map(0) {}
Endpoint 633481e928a62d4bb14edf18
Item createion timesta 1664701658375
Map(0) {}
Endpoint 633481e928a62d4bb14edf1b
Item createion timesta 1664701658375
Map(0) {}
Endpoint 633481e928a62d4bb14edf1e
Item createion timesta 1664701658376
Map(0) {}
Endpoint 633481e928a62d4bb14edf21
Item createion timesta 1664701658376
Map(0) {}
Endpoint 633481e928a62d4bb14edf24
Item createion timesta 1664701658377
Map(0) {}
Endpoint 633889e10123935a23e98f79
Item createion timesta 1664701658378
Map(0) {}
```

**Comment by mStirner** [comment]
![grafik](https://user-images.githubusercontent.com/5003424/193447216-a765a4e6-7761-4592-b6a3-5c51af1551f4.png)
![grafik](https://user-images.githubusercontent.com/5003424/193447241-5e672d23-59e0-408d-9884-82e424a5e237.png)
![grafik](https://user-images.githubusercontent.com/5003424/193447294-73d29747-db83-4e52-87f9-7fed81c69425.png)

Seems like the custom `res.json` function in combination with the helper function `_iterate` are creating a new array with shallow copy of the content/reference. This overrides the custom handler set in the "Commands" class, since a new Instance is created.

Solution: Rewrite the component and drop custom array implementation, handle custom command handler/implementation on command class level. 

Let a array, be array and do not extend it!
