### ISSUE TITLE
RangeError: Invalid WebSocket frame: RSV1 must be clear

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#199]
```
[ws://lowboard.lan:8080] RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:184:14)
    at Receiver.startLoop (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Receiver.Writable.write (node:internal/streams/writable:336:10)
    at Duplexify.socketOnData (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/websocket.js:1153:35)
    at Duplexify.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}
```

In the lowboard plugin, source code:
```js
        const device = C_DEVICES.items.find((device) => {
            return device._id === "633c88c10d18aa66e28df82e";
        });

        if (!device) {

        }

        const endpoint = C_ENDPOINTS.items.find((endpoint) => {
            return endpoint.device === device._id;
        });

        let iface = device.interfaces[0];

        iface.on("attached", (socket) => {

            //let agent = iface.httpAgent();
            let agent = new Agent();
            agent.createConnection = () => {
                console.log(">>>>>>> createConnectoin called")
                //let socket = iface.upstream;
                socket.ref = (...args) => { console.log("socket.ref called", ...args); };
                socket.unref = (...args) => { console.log("socket.unref called", ...args); };
                socket.setKeepAlive = (...args) => { console.log("socket.setKeepAlive called", ...args); };
                socket.setTimeout = (...args) => { console.log("socket.setTimeout called", ...args); };
                socket.setNoDelay = (...args) => { console.log("socket.setNoDelay called", ...args); };
                return socket;
            }


            let ws = new WebSocket(`ws://${iface.settings.host}:${iface.settings.port}`, {
                agent
            });

            ws.on("error", (err) => {
                console.error("[%s]", ws.url, err);
            });

            ws.on("pong", () => {
                console.log("Pong received");
            })

            ws.on("open", () => {
                console.log("WebSocket connected to:", ws.url);


                setInterval(() => {
                    ws.ping();
                }, 1000);


                //ws.send(`{"fx":"rainbow"}`);

                endpoint.commands.forEach((command) => {
                    command.setHandler((cmd, iface, params, done) => {
                        if (ws.readyState === 1) {

                            console.log("send payload", cmd)

                            // payload = json string
                            ws.send(`${cmd.playload}`);

                            done(null, true)

                        } else {

                            done(new Error("NOT_READY"));

                        }
                    });
                });

            });

        });
```

I think i had this issue before, when something in the middleware streams was set like "decodeString" or "objecMode".
I cant currently resolve the issue. A playground repo with working Websocket over Websocket briding can be found here: https://github.com/OpenHausIO/playground

eISCP Controlling for my Pioneer AV Receiver works too, so does the WS & RESTFul API for my ZigBee Gateway does.
So not sure why my custom express (lowboard) API does break the backend when the websocket connection is tunneld.

Ping & Pong events to the lowboard target works well too...
If this is a error with the target device/api, how to catch this in the backend correctly?

**NOTE: Perhaps try the same ws verions in playground & backend, Major version differs for +/-1.
Could also be a "bug"/outdated version in lowboard API.**

**Comment by mStirner** [comment]
If it does not work with a newer version: How about to wrap the data transmitted through the InterfaceStream in base64?
On WebSocket connection, could be passed as "protocol" (https://github.com/websockets/ws/blob/HEAD/doc/ws.md#new-websocketaddress-protocols-options: `protocols` & https://github.com/websockets/ws/blob/HEAD/doc/ws.md#new-websocketserveroptions-callback: `handleProtocols`)

**Comment by mStirner** [comment]
A quick test with the plugin, seems like the problem was the command handler and how the device/commands are added:
```js
                C_ENDPOINTS.add({
                    device: device._id,
                    name: "Lowboard",
                    commands: [{
                        interface: device.interfaces[0]._id,
                        name: "FX = Rainbow",
                        alias: "FX_RAINBOW",
                        payload: JSON.stringify({
                            fx: "rainbow"
                        })
                    }, {
                        interface: device.interfaces[0]._id,
                        name: "FX = Straight",
                        alias: "FX_OFF",
                        payload: JSON.stringify({
                            fx: "straight"
                        })
                    }, {
                        interface: device.interfaces[0]._id,
                        name: "FX = Lightning",
                        alias: "FX_OFF",
                        payload: JSON.stringify({
                            fx: "lightning"
                        })
                    }, {
                        interface: device.interfaces[0]._id,
                        name: "FX = Aus",
                        alias: "FX_OFF",
                        payload: JSON.stringify({
                            fx: "clear"
                        })
                    }]
                });
```

In the command handler then it neccessery to parse & stringy the command payload before sending it:
```js
                endpoint.commands.forEach((command) => {
                    command.setHandler((cmd, iface, params, done) => {
                        if (ws.readyState === 1) {

                            console.log("send payload", cmd, cmd.payload)

                            let data = JSON.parse(cmd.payload);
                            let str = JSON.stringify(data);

                            // payload = json string
                            ws.send(str);

                            //ws.send(`{"fx":"rainbow"}`);

                            done(null, true)

                        } else {

                            done(new Error("NOT_READY"));

                        }
                    });
                });
```

A simple `ws.send(cmd.payload)` or ```ws.send(`${cmd.paload}`)``` did not work.

- https://github.com/mStirner/oh-plg-lowboard
