### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#238]
On my local deployment test, updating to v2 the following error shows up:

```
Nov 27 19:35:46 open-haus.lan node[19177]: /opt/OpenHaus/backend-v2.0.0/components/store/class.store.js:33
Nov 27 19:35:46 open-haus.lan node[19177]:         this.config = obj.config.map((data) => {
Nov 27 19:35:46 open-haus.lan node[19177]:                                  ^
Nov 27 19:35:46 open-haus.lan node[19177]: TypeError: Cannot read properties of undefined (reading 'map')
Nov 27 19:35:46 open-haus.lan node[19177]:     at new Store (/opt/OpenHaus/backend-v2.0.0/components/store/class.store.js:33:34)
Nov 27 19:35:46 open-haus.lan node[19177]:     at /opt/OpenHaus/backend-v2.0.0/components/store/index.js:78:24
Nov 27 19:35:46 open-haus.lan node[19177]:     at Array.map (<anonymous>)
Nov 27 19:35:46 open-haus.lan node[19177]:     at /opt/OpenHaus/backend-v2.0.0/components/store/index.js:77:25
Nov 27 19:35:46 open-haus.lan node[19177]:     at /opt/OpenHaus/backend-v2.0.0/node_modules/mongodb/lib/utils.js:348:28
Nov 27 19:35:46 open-haus.lan node[19177]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mStirner** [comment]
Comes from old schema:
```js
OpenHaus [direct: primary] OpenHaus> db.store.find()
[
  {
    _id: ObjectId("6283effb323aeb5f1a1e3a3b"),
    key: 'interval',
    description: 'API Polling interval',
    namespace: 'd11e7f38-91cb-4f32-89e8-3452f624bb47',
    value: 3000,
    timestamps: { created: 1652813819453, updated: null }
  }
]
```
How migrate that?!
