### ISSUE TITLE
Error: Not found

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#239]
```
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.257][debug][plugins/32f44273-3ff8-452c-a087-34c4b4b67e62] ssdp item with target NT found!
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.260][debug][plugins/32f44273-3ff8-452c-a087-34c4b4b67e62] Gateway found: "Phoscon Gateway"
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.261][debug][plugins/32f44273-3ff8-452c-a087-34c4b4b67e62] Update Endpoints assigned to Gateway
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.266][verbose][system] Start plugin "Aten VS0801H" (fd9d4247-8a39-4e73-a902-bf388632eb21)
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.267][debug][system] 2/2 Plugins started
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.267][info][system] Startup complete
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.269][verbose][vault] update(); "Reject" in worker code called
Nov 27 19:48:02 open-haus.lan node[29319]: [2022.11.27 - 19:48.02.269][debug][vault] update(); Function stack catched/rejected
Nov 27 19:48:02 open-haus.lan node[29319]: node:internal/process/promises:279
Nov 27 19:48:02 open-haus.lan node[29319]:             triggerUncaughtException(err, true /* fromPromise */);
Nov 27 19:48:02 open-haus.lan node[29319]:             ^
Nov 27 19:48:02 open-haus.lan node[29319]: Error: Not found
Nov 27 19:48:02 open-haus.lan node[29319]:     at /opt/OpenHaus/backend-v2.0.0/system/component/class.component.js:471:39
Nov 27 19:48:02 open-haus.lan node[29319]:     at new Promise (<anonymous>)
Nov 27 19:48:02 open-haus.lan node[29319]:     at /opt/OpenHaus/backend-v2.0.0/system/component/class.component.js:463:24
Nov 27 19:48:02 open-haus.lan node[29319]:     at /opt/OpenHaus/backend-v2.0.0/system/component/class.common.js:145:32
Nov 27 19:48:02 open-haus.lan node[29319]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

If a no found is thrown, the server should not crash!

**Comment by mStirner** [comment]
```
[2022.11.30 - 20:45.28.611][verbose][rooms] update(); "Reject" in worker code called
Error: Not found
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:471:39
    at new Promise (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:463:24
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:145:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[2022.11.30 - 20:45.28.611][debug][rooms] update(); Function stack catched/rejected
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Not found
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:471:39
    at new Promise (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:463:24
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:145:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[nodemon] app crashed - waiting for file changes before starting...
```
```js
        C_ROOMS.update("adsjajdsf", {
            bla: true
        });
```

**Comment by mStirner** [comment]
```
[2022.11.30 - 20:46.49.539][verbose][rooms] update(); "Reject" in worker code called
Error: Not found
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:471:39
    at new Promise (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:463:24
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:145:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[2022.11.30 - 20:46.49.539][debug][rooms] update(); Function stack catched/rejected


```
```js
        C_ROOMS.update("adsjajdsf", {
            bla: true
        }, () => { });
```

Did i just forget to catch somewhere the promise?

**Comment by mStirner** [comment]
Remove the first error display and it should be fine.
```
[2022.11.30 - 20:54.28.567][verbose][rooms] update(); "Reject" in worker code called
Error: Not found
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:471:39
    at new Promise (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:463:24
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:145:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error thrown Error: Not found
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:471:39
    at new Promise (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:463:24
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:145:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022.11.30 - 20:54.28.568][debug][rooms] update(); Function stack catched/rejected
```

```js
        C_ROOMS.update("adsjajdsf", {
            bla: true
        }, (err) => {
            console.log("Error thrown", err);
        });
```

**Comment by mStirner** [comment]
Try/catch does not work for function:
```
[2022.11.30 - 21:02.40.747][verbose][rooms] update(); "Reject" in worker code called
Error: Not found
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:471:39
    at new Promise (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:463:24
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:145:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[2022.11.30 - 21:02.40.747][debug][rooms] update(); Function stack catched/rejected
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Not found
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:471:39
    at new Promise (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/system/component/class.component.js:463:24
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:145:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[nodemon] app crashed - waiting for file changes before starting...
```
```js
        try {

            C_ROOMS.update("adsjajdsf", {
                bla: true
            });

        } catch (err) {
            console.log("ASDFASDFASDFA", err)
        }
```

Investigate where the error is thrown and why its not catched.

**Comment by mStirner** [comment]
`class.common.js` update changes:
```js

                    try {

                        logger.warn("asdfasdf");

                        args = await preHooks(args.slice(0, end)).catch((err) => {

                            logger.verbose(`${name}(); "Reject" in pre hooks called`, err);

                            throw err;

                        });

                        args = await worker(...args).catch((err) => {

                            //console.log("Worker code rejected", err);
                            console.log(`${name}(); "Reject" in worker code called`, err);

                            //Promise.reject(err);
                            throw err;

                        });

                        args = await postHooks(args).catch((err) => {

                            logger.verbose(`${name}(); "Reject" in post hooks called`, err);

                            throw err;

                        });

                        final(...args)

                        // "resolve" promisify 
                        done(null, ...args);

                        this.events.emit(name, ...args);

                    } catch (err) {

                        console.log("Catched", err);

                        done(err);

                    }
```
