### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#243]
`[DELETE] http://{{HOST}}:{{PORT}}/api/plugins/638781616f8a3eedc4832a63` shows:

```
TypeError: Cannot read properties of undefined (reading '0')
    at EventEmitter.<anonymous> (/home/marc/projects/OpenHaus/backend/routes/router.api.events.js:47:27)
    at EventEmitter.emit (node:events:525:35)
    at /home/marc/projects/OpenHaus/backend/system/component/class.common.js:180:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mStirner** [comment]
Removed `data: args[0]`.
If argument array is available, why need for "data"?
