### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#248]
```
User request: null false false 127.0.0.1 POST /endpoints/638908de9df8f7785340d803/commands/638908de9df8f7785340d804
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Binary
    at new NodeError (node:internal/errors:387:5)
    at _write (node:internal/streams/writable:314:13)
    at InterfaceStream.Writable.write (node:internal/streams/writable:336:10)
    at Command.<anonymous> (/home/marc/projects/OpenHaus/backend/components/endpoints/class.command.js:91:19)
    at Command.trigger (/home/marc/projects/OpenHaus/backend/components/endpoints/class.command.js:202:16)
    at /home/marc/projects/OpenHaus/backend/routes/router.api.endpoints.js:30:21
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
Command timedout! Execution was not successful, worker function: [Function (anonymous)]
node:_http_outgoing:644
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/response.js:278:15)
    at ServerResponse.res.json (/home/marc/projects/OpenHaus/backend/routes/rest-handler.js:26:18)
    at /home/marc/projects/OpenHaus/backend/routes/router.api.endpoints.js:32:21
    at /home/marc/projects/OpenHaus/backend/components/endpoints/class.command.js:190:17
    at Timeout._onTimeout (/home/marc/projects/OpenHaus/backend/helper/timeout.js:47:13)
    at listOnTimeout (node:internal/timers:559:17) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mStirner** [comment]
```
User request: null false false 127.0.0.1 POST /endpoints/63a0ce5b33d59ec69d8ffe18/commands/63a0ce5b33d59ec69d8ffe19
TypeError: Cannot read properties of undefined (reading 'write')
    at Command.<anonymous> (/home/marc/projects/OpenHaus/backend/components/endpoints/class.command.js:98:19)
    at Command.trigger (/home/marc/projects/OpenHaus/backend/components/endpoints/class.command.js:209:16)
    at /home/marc/projects/OpenHaus/backend/routes/router.api.endpoints.js:42:21
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:284:15
    at param (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:365:14)
    at paramCallback (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:412:21)
Command timedout! Execution was not successful, worker function: [Function (anonymous)]
node:_http_outgoing:644
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/response.js:278:15)
    at ServerResponse.res.json (/home/marc/projects/OpenHaus/backend/routes/rest-handler.js:30:18)
    at /home/marc/projects/OpenHaus/backend/routes/router.api.endpoints.js:44:21
    at /home/marc/projects/OpenHaus/backend/components/endpoints/class.command.js:197:17
    at Timeout._onTimeout (/home/marc/projects/OpenHaus/backend/helper/timeout.js:47:13)
    at listOnTimeout (node:internal/timers:559:17) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

Happend while try to set effect on lowboard led stripe, without mounted plugin:
```
[2022.12.23 - 17:41.09.659][verbose][system] Start plugin "Lowboard" (32ae791a-a073-4c2c-a2e9-1a9ca0d572ed)
[2022.12.23 - 17:41.09.660][error][system] Could not found plugin file/folder "32ae791a-a073-4c2c-a2e9-1a9ca0d572ed"
[2022.12.23 - 17:41.09.660][warn][system] Could not boot plugin "Lowboard" (32ae791a-a073-4c2c-a2e9-1a9ca0d572ed)
[2022.12.23 - 17:41.09.660][verbose][system] Start plugin "Pioneer&#x2F;Onkyo" (83d9f467-a201-41a4-aa08-3f39da5d0637)
[2022.12.23 - 17:41.09.660][error][system] Could not found plugin file/folder "83d9f467-a201-41a4-aa08-3f39da5d0637"
[2022.12.23 - 17:41.09.660][warn][system] Could not boot plugin "Pioneer&#x2F;Onkyo" (83d9f467-a201-41a4-aa08-3f39da5d0637)
[2022.12.23 - 17:41.09.660][verbose][system] Start plugin "Phoscon Gateway" (8f00a50c-39dc-408d-a621-b56363ab2b69)
[2022.12.23 - 17:41.09.660][error][system] Could not found plugin file/folder "8f00a50c-39dc-408d-a621-b56363ab2b69"
[2022.12.23 - 17:41.09.660][warn][system] Could not boot plugin "Phoscon Gateway" (8f00a50c-39dc-408d-a621-b56363ab2b69)
[2022.12.23 - 17:41.09.660][verbose][system] Start plugin "Samsung TV" (ac19271c-82b2-11ed-9028-c3c23c2befc8)
```
