### ISSUE TITLE
Crash when decrypt on `null` value is called

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#260]
```
/opt/OpenHaus/backend-v2.0.0/components/vault/decrypt.js:1
const crypto=require("crypto");function decrypt(e){var[e,r,t]=e.split(":"),e=Buffer.from(e,"hex"),r=Buffer.from(r,"hex"),r=crypto.scryptSync(process.env.VAULT_MASTER_PASSWORD,r,Number(process.env.VAULT_KEY_BYTE_LEN)),r=crypto.createDecipheriv(process.env.VAULT_BLOCK_CIPHER,r,e,{authTagLength:Number(process.env.VAULT_AUTH_TAG_BYTE_LEN)}),e=r.update(t,"hex","utf8");return(e+=r.final("utf8")).toString()}module.exports=decrypt;
                                                                ^

TypeError: Cannot read properties of null (reading 'split')
    at decrypt (/opt/OpenHaus/backend-v2.0.0/components/vault/decrypt.js:1:65)
    at Secret.decrypt (/opt/OpenHaus/backend-v2.0.0/components/vault/class.secret.js:1:625)
    at /opt/OpenHaus/backend-v2.0.0/plugins/39a38e4b-5460-4897-95f8-872b550ea45b/endpoint-handler.js:45:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

When vault item has no value, split does not work and so the whole decrypt method crashes.

**Comment by mStirner** [comment]
After setting the values via mongodb compass directly, the backend starts.

Issue confirmed.
