### ISSUE TITLE
HTTP/UNIX Socket diffrence?

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#279]
Are there any diffrence when a request is made to tcp socket or unix socket?

Works:
```
curl -X PUT -d '{"name": "Administrator", "email": "admin@example.net", "password": "Pa$$w0rd", "admin": true, "enabled": true}' -H "Content-type: application/json" --unix-socket /tmp/open-haus.sock http://localhost:8080/api/users
```

Dont:
```
curl -X POST -d '{"email": "admin@example.net", "password": "Pa$$w0rd"}' -H "Content-type: application/json" --unix-socket /tmp/open-haus.sock http://localhost:8080/auth/login
```

After restarting the container, login works too.

- [x] Check if there are any difference between tcp & unix socket
- [x] Investigate why in "cloud.open-haus.lan" this only works after a restart

Login attempt shows:
```
[2023.01.24 - 20:40.56.867][error][users] Could not compare password for user "Administrator" (admin@example.net)
```
After restarting:
```
 curl -X POST -d '{"email": "admin@example.org", "password": "Pa$$w0rd"}' -H "Content-type: application/json" --unix-socket /tmp/open-haus.sock http://localhost:8080/auth/login
{"token":"eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUub3JnIiwidXVpZCI6IjM1NTA2N2M0LTljMjctMTFlZC05Njk2LTNiZGRiZmY2NzU3ZSIsImlhdCI6MTY3NDU5MjkzMX0.MB3iplLzLe2AZgVQpnBlc_kRl54B3F8wZ9cn2uIxcy6ZysNGpTGU2cviNigIwneq","success":true}
```

**Comment by mStirner** [comment]
```
[2023.01.28 - 13:09.49.056][debug][users] Login user "admin@example.net"
[2023.01.28 - 13:09.49.056][error][users] Could not compare password for user "Administrator" (admin@example.net)
Error: data and hash arguments required
    at Object.compare (/home/marc/projects/OpenHaus/backend/node_modules/bcrypt/bcrypt.js:208:17)
    at /home/marc/projects/OpenHaus/backend/components/users/index.js:129:20
    at /home/marc/projects/OpenHaus/backend/helper/promisify.js:13:9
    at new Promise (<anonymous>)
    at promisfy (/home/marc/projects/OpenHaus/backend/helper/promisify.js:12:19)
    at C_USERS.login (/home/marc/projects/OpenHaus/backend/components/users/index.js:109:16)
    at /home/marc/projects/OpenHaus/backend/routes/router.auth.js:48:17
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)

**Comment by mStirner** [comment]
Problem is not the unix socket.
Its the password nulling when user items returned via http:

https://github.com/OpenHausIO/backend/blob/4395f7e562109a77ae30b8118e3e9add48b8a700/routes/rest-handler.js#L22-L24

When user items returned due to the password setting to null, its not possible to compare the password anymore.
