### ISSUE TITLE
TypeError: s.cmd.trigger is not a function

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#287]
```
TypeError: s.cmd.trigger is not a function
    at /opt/OpenHaus/backend/routes/router.api.endpoints.js:1:431
    at Layer.handle [as handle_request] (/opt/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/opt/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/opt/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at /opt/OpenHaus/backend/node_modules/express/lib/router/index.js:284:15
    at param (/opt/OpenHaus/backend/node_modules/express/lib/router/index.js:365:14)
    at paramCallback (/opt/OpenHaus/backend/node_modules/express/lib/router/index.js:412:21)
    at /opt/OpenHaus/backend/routes/router.api.endpoints.js:1:212
    at paramCallback (/opt/OpenHaus/backend/node_modules/express/lib/router/index.js:415:7)
```

After adding binary command payload via api:
```json
{
    "_id": "63d3058afa6847597d5c8c1a",
    "name": "Mirror",
    "device": "63d3056bfa6847597d5c8c18",
    "room": "63d2c39f2f9507ca2d2d24f7",
    "icon": "fa-regular fa-square",
    "commands": [
        {
            "name": "On",
            "payload": "on",
            "alias": "on",
            "interface": "63d3056bfa6847597d5c8c19",
            "_id": "63d3058afa6847597d5c8c1b",
            "identifier": null,
            "description": null
        },
        {
            "name": "Off",
            "payload": "off",
            "alias": "off",
            "interface": "63d3056bfa6847597d5c8c19",
            "_id": "63d3058afa6847597d5c8c1c",
            "identifier": null,
            "description": null
        },
        {
            "name": "Binary",
            "payload": {
                "type": "Buffer",
                "data": []
            },
            "alias": "Binary",
            "interface": "63d3056bfa6847597d5c8c19",
            "_id": "63d7b40883115989b9ae946d",
            "identifier": null,
            "description": null
        }
    ],
    "timestamps": {
        "created": 1674773898230,
        "updated": 1675080712139
    },
    "enabled": true,
    "states": [],
    "identifier": null
}
```
`http://{{HOST}}:{{PORT}}/api/endpoints/63d3058afa6847597d5c8c1a`

**Comment by mStirner** [comment]
Could this be, because the commands array is not iterated and a new [`Command`](https://github.com/OpenHausIO/backend/blob/e6a1a98c4eaf389e6681991544725fe24813f799/components/endpoints/class.command.js) class is created after updating?

**Comment by mStirner** [comment]
Yup, quick messing arround, potential post updating instance creating:

Add to: https://github.com/OpenHausIO/backend/blob/e6a1a98c4eaf389e6681991544725fe24813f799/system/component/class.component.js#L40
```js
        let classMappings = new Map();

        Object.defineProperty(this, "_setClassInstance", {
            value: (prop, cls) => {
                classMappings.set(prop, cls);
            },
            configurable: false,
            writable: false,
            enumerable: false
        });

        this.hooks.post("update", (data, next) => {

            console.log("POST item creation");

            Object.keys(data).forEach((key) => {
                if (classMappings.has(key)) {

                    console.log("Check for class instances for", key);
                    let Cls = classMappings.get(key);

                    data[key] = data[key].map((obj) => {
                        if (obj instanceof Cls) {
                            return obj;
                        } else {
                            console.log("Create new instance for", obj)
                            return new Cls(obj);
                        }
                    });

                }
            });

            next(null, data);

        });
```

In the component then:
```js
        // create a class instance,
        // after the arrays have new items
        this._setClassInstance("states", State);
        this._setClassInstance("commands", Command);
```

**Comment by mStirner** [comment]
Other possible solution:

__class.endpoint.js__
```js
class Endpoint {
    constructor(obj) {

        Object.assign(this, obj);
        this._id = String(obj._id);

        //this.commands = new Commands(obj.commands);
        //this.states = new States(obj.states);

        /*
        // this causes bug #287
        this.states = obj.states.map((item) => {
            return new State(item);
        });

        this.commands = obj.commands.map((item) => {
            return new Command(item);
        });
        */


        obj.states.forEach((item, i, arr) => {
            arr[i] = new State(item);
        });

        obj.commands.forEach((item, i, arr) => {
            arr[i] = new Command(item);
        });

        this.states = new Proxy(obj.states, {
            set(target, prop, value, receiver) {

                if (prop === "length") {
                    target.forEach((v, i, arr) => {
                        if (!(v instanceof State)) {
                            arr[i] = new State(v);
                        }
                    });
                }

                return Reflect.set(target, prop, value, receiver);

            }
        });


        this.commands = new Proxy(obj.commands, {
            set(target, prop, value, receiver) {

                if (prop === "length") {
                    target.forEach((v, i, arr) => {
                        if (!(v instanceof Command)) {
                            arr[i] = new Command(v);
                        }
                    });
                }

                return Reflect.set(target, prop, value, receiver);

            }
        });

        //this.setHandler = _expose(this.commands, "setHandler");
        //this.getHandler = _expose(this.commands, "getHandler");
        //this.setState = _expose(this.states, "setState");

        //this.method1 = _expose(this.commands, "method1");
        //this.method2 = _expose(this.states, "method2");

        Object.defineProperty(this, "trigger", {
            value: _expose(this.commands, "trigger"),
            enumerable: false,
            configurable: false,
            writable: false
        });

    }
};
```

**Comment by mStirner** [comment]
Or as component post update hooks (not tested):

```js

        this.hooks.post("update", (_id, data, next) => {

            data.commands.forEach((v, i, arr) => {
                if (!(v instanceof Command)) {
                    arr[i] = new Command(v);
                }
            });

            data.commands.forEach((v, i, arr) => {
                if (!(v instanceof State)) {
                    arr[i] = new State(v);
                }
            });

            next(null, _id, data);

        });
```

Feels like this is better than any approach with proxys & setter
