### ISSUE TITLE
Error: Header must be 12 bytes

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#292]
```
/home/marc/projects/OpenHaus/backend/node_modules/dns-packet/index.js:157
  if (buf.length < 12) throw new Error('Header must be 12 bytes')
                       ^

Error: Header must be 12 bytes
    at Object.header.decode (/home/marc/projects/OpenHaus/backend/node_modules/dns-packet/index.js:157:30)
    at exports.decode (/home/marc/projects/OpenHaus/backend/node_modules/dns-packet/index.js:1562:25)
    at WebSocket.<anonymous> (/home/marc/projects/OpenHaus/backend/routes/router.api.mqtt.js:58:47)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:513:14)
    at Receiver.getData (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/marc/projects/OpenHaus/backend/node_modules/ws/lib/receiver.js:83:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mStirner** [comment]
This happened because a stupid developer while developing the mqtt component :D
