### ISSUE TITLE
Uncaught rejection catched! Error: error:06065064:digital envelope 

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#302]
```
backend    | [2023.02.16 - 18:55.36.697][error][plugins/8f00a50c-39dc-408d-a621-b56363ab2b69] Could not setup device handling!
backend    | [2023.02.16 - 18:55.36.762][error][plugins/8f00a50c-39dc-408d-a621-b56363ab2b69] Could not setup endpoint handling!
backend    | [2023.02.16 - 18:55.36.768][info][system] 4/4 Plugins started
backend    | [2023.02.16 - 18:55.36.768][info][system] Startup complete
backend    | [2023.02.16 - 18:55.36.834][error][system] Uncaught rejection catched! Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
backend    |     at Decipheriv.final (node:internal/crypto/cipher:193:29)
backend    |     at e (/opt/OpenHaus/backend/components/vault/decrypt.js:1:358)
backend    |     at n.decrypt (/opt/OpenHaus/backend/components/vault/class.secret.js:1:703)
backend    |     at /opt/OpenHaus/backend/plugins/39a38e4b-5460-4897-95f8-872b550ea45b/endpoint-handler.js:45:43
backend    |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
backend    |   library: 'digital envelope routines',
backend    |   function: 'EVP_DecryptFinal_ex',
backend    |   reason: 'bad decrypt',
backend    |   code: 'ERR_OSSL_EVP_BAD_DECRYPT'
backend    | }
```

Copied plugin folder from local test system to docker container.
I guess that happens because no credentials are present, which is fine per se.

Just catch the "Uncaught rejection" so it does not bubble further  and crashes the app.

**Comment by mStirner** [comment]
Secrets are present, but where copied via dump/export.
Could this happen when import/exported from on machine to another?

**Comment by mStirner** [comment]
https://stackoverflow.com/questions/70093261/encrypt-decrypt-data-err-ossl-evp-bad-decrypt

**Comment by mStirner** [comment]
Because of bad password? When run from the shell, `$` must be prefixed with a backslash `\`.
