### ISSUE TITLE
Check if plugins file/folder exists before load/require

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#31]
Check if a plugin file/folder exsits before to require/load.
Backends crash if file is not found:

```sh
$ npm run start

> backend@1.0.0 start
> ./node_modules/.bin/nodemon index.js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
Starting OpenHaus v1.0.0...
Error in plugin: Error: Cannot find module '/home/marc/projects/OpenHaus/backend/plugins/d11e7f38-91cb-4f32-89e8-3452f624bb47/index.js'
Require stack:
- /home/marc/projects/OpenHaus/backend/components/plugins/class.plugin.js
- /home/marc/projects/OpenHaus/backend/components/plugins/index.js
- /home/marc/projects/OpenHaus/backend/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Plugin.boot (/home/marc/projects/OpenHaus/backend/components/plugins/class.plugin.js:38:30)
    at /home/marc/projects/OpenHaus/backend/index.js:361:20
    at Array.forEach (<anonymous>)
    at /home/marc/projects/OpenHaus/backend/index.js:356:8
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/marc/projects/OpenHaus/backend/components/plugins/class.plugin.js',
    '/home/marc/projects/OpenHaus/backend/components/plugins/index.js',
    '/home/marc/projects/OpenHaus/backend/index.js'
  ]
}

```

**Comment by mStirner** [comment]
Fixed/implemented locally.
