### ISSUE TITLE
trigger a scene via http API crashes

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#362]
```
TypeError: Cannot read properties of undefined (reading 'bind')
    at /home/marc/projects/OpenHaus/backend/components/scenes/class.scene.js:106:34
    at Array.map (<anonymous>)
    at Scene.trigger (/home/marc/projects/OpenHaus/backend/components/scenes/class.scene.js:103:12)
    at /home/marc/projects/OpenHaus/backend/routes/router.api.scenes.js:5:18
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:284:15
    at param (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:365:14)
```

**Comment by mStirner** [comment]
**This only happens when the scene contains a command makro, which points to a endpoint that does no longer exists.**
