### ISSUE TITLE
Updateiting/adding scene triggers could not work

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#390]
https://github.com/OpenHausIO/backend/blob/185a48013e6a4cfe46f0140e50e31423b513e79a/components/scenes/index.js#L26-L38

Since the triggers array is not checked, its possible that new added triggers do not work properly because they are not a instance of the trigger class.

**Comment by mStirner** [comment]
Breaks when updated/added.

```
TypeError: trigger.fire is not a function
    at /home/marc/projects/OpenHaus/backend/routes/router.api.webhooks.js:45:21
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:284:15
    at param (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:365:14)
    at paramCallback (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:412:21)
    at /home/marc/projects/OpenHaus/backend/routes/rest-handler.js:87:17
    at /home/marc/projects/OpenHaus/backend/helper/promisify.js:31:13
```
