### ISSUE TITLE
Cant start plugin after adding it via HTTP API

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#444]
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read properties of undefined (reading &#39;uuid&#39;)<br> &nbsp; &nbsp;at /home/marc/projects/OpenHaus/backend/routes/router.api.plugins.js:11:70<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:328:13)<br> &nbsp; &nbsp;at /home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:346:12)<br> &nbsp; &nbsp;at next (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:280:10)<br> &nbsp; &nbsp;at /home/marc/projects/OpenHaus/backend/routes/rest-handler.js:62:13<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:328:13)<br> &nbsp; &nbsp;at /home/marc/projects/OpenHaus/backend/node_modules/express/lib/router/index.js:286:9</pre>
</body>
</html>
```

**Comment by mStirner** [comment]
While working on the issue #436 i added a middleware function to the `router.api.plugins.js`.
This router is (weis der teufel warum) executed before the `router.params()` function in the `rest-handler.js`:

```js
    router.use((req, res, next) => {

        console.log("2) plugin middleware", C_PLUGINS.items, req.item, req.params);



        req.install = req.params?.install === "true" || false;
        req.folder = path.join(process.cwd(), "plugins", req.item?.uuid || "");


        console.log("Install:", req.install);
        console.log("Folder", req.folder);

        next();

    });
```

Because its executed before the rest-handler stuff, `req.item` is undefined.
Unfortunatly, `req.params` is also undefined, so a workaround is not possible here.
