### ISSUE TITLE
Fix plugin startup handling/error message

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#97]
If a plugin is enabled in the database but does not exists on the filesystem, it says "plugin x/y started" but thats not possible:
```
Starting OpenHaus v1.0.0...
[2022.03.27 - 23:49.26.538][debug][system] Init Database...
[2022.03.27 - 23:49.26.540][verbose][system] Connecting to "mongodb://127.0.0.1:27017/OpenHaus"...
[2022.03.27 - 23:49.26.570][info][system] Connected to "mongodb://127.0.0.1:27017/OpenHaus"
[2022.03.27 - 23:49.26.571][debug][system] Init components...
[2022.03.27 - 23:49.26.571][verbose][system] Starting component "devices"
[2022.03.27 - 23:49.26.659][verbose][system] Starting component "rooms"
[2022.03.27 - 23:49.26.664][verbose][system] Starting component "endpoints"
[2022.03.27 - 23:49.26.671][verbose][system] Starting component "plugins"
[2022.03.27 - 23:49.26.675][verbose][system] Starting component "vault"
[2022.03.27 - 23:49.26.695][debug][system] Component "devices" ready to use. (1/5)
[2022.03.27 - 23:49.26.698][debug][system] Component "rooms" ready to use. (2/5)
[2022.03.27 - 23:49.26.700][debug][system] Component "endpoints" ready to use. (3/5)
[2022.03.27 - 23:49.26.702][debug][system] Component "vault" ready to use. (4/5)
[2022.03.27 - 23:49.26.703][debug][system] Component "plugins" ready to use. (5/5)
[2022.03.27 - 23:49.26.703][info][system] All 5 Components ready
[2022.03.27 - 23:49.26.703][debug][system] Init http server...
[2022.03.27 - 23:49.26.811][info][system] HTTP Server listening on http://0.0.0.0:8080
[2022.03.27 - 23:49.26.812][info][system] Initzisalision done
[2022.03.27 - 23:49.26.812][debug][system] Starting plugins...
[2022.03.27 - 23:49.26.812][verbose][system] Start plugin "ZigBee Gateway (DeCONz)" (d11e7f38-91cb-4f32-89e8-3452f624bb47)
[2022.03.27 - 23:49.26.813][error][system] Could not found plugin file/folder "d11e7f38-91cb-4f32-89e8-3452f624bb47"
[2022.03.27 - 23:49.26.814][warn][system] Error in plugin "ZigBee Gateway (DeCONz)":  Error: Plugin not found
    at Plugin.boot (/opt/OpenHaus/backend/components/plugins/class.plugin.js:1:555)
    at /opt/OpenHaus/backend/index.js:1:5014
    at Array.forEach (<anonymous>)
    at /opt/OpenHaus/backend/index.js:1:4941
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022.03.27 - 23:49.26.815][debug][system] 1/1 Plugins started
[2022.03.27 - 23:49.26.815][info][system] Startup complete
```

**Comment by mStirner** [comment]
This `try/catch` block does not what it should do
```js
    bootable.forEach((plugin) => {
        try {

            logger.verbose(`Start plugin "${plugin.name}" (${plugin.uuid})`);

            plugin.boot();

            started += 1;

        } catch (err) {

            logger.warn(`Could not boot plugin "${plugin.name}" (${plugin.uuid})`);

        }
    });
```

See https://github.com/OpenHausIO/backend/blob/dev/index.js#L427

The "could not boot plugin x" message is not shown.

**Comment by mStirner** [comment]
#130
